In [235]:
import numpy as np

5, 5 크기의 정수 데이터 생성

In [236]:
np.random.seed(0)
data = np.random.randint(10, size = (5,5))
data

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4]])

각 행은 각각의 확률 분포의 등장 횟수,

표본의 추출 횟수는 모든 행들의 합, N

In [237]:
N = np.sum(data)
N

135

각각의 취할 수 있는 값들에 대해서 X = xi, Y = yj 인 시도의 횟수는 data 행렬의 data[i,j] 요소

In [238]:
for i in range(data.shape[0]):
  for j in range(data.shape[1]):
    data[i, j]

X = xi 인 시도를 x_i, Y = yj 인 시도의 숫자를 y_i로 표현한다.

In [239]:
sum_x = 0
sum_y = 0

x_i = []
y_i = []

for i in range(data.shape[0]):
  sum_x = 0
  sum_y = 0
  for j in range(data.shape[1]):
    sum_x += data[i][j]
    sum_y += data[j][i]
  x_i.append(sum_x)
  y_i.append(sum_y)

In [240]:
x_i

[18, 23, 30, 29, 35]

In [241]:
y_i

[32, 25, 31, 30, 17]

X가 xi, Y가 yj 일 확률을 p(X=xi, Y=yj) 로 적고 이를 X=xi, Y=yj 일 결합 확률이라 한다.

이는 i, j 칸에 있는 포인트의 숫자를 전체 포인트들의 숫자로 나눠서 구할 수 있다.

In [242]:
def joint_probability(data, i, j):
  """
  X=xi, Y=yj 일 결합 확률
  Args:
    data : 행렬 형태의 전체 데이터
    i : 행의 개수
    j : 열의 개수
  Return
    X=xi, Y=yj 일 결합 확률값
  """
  N = np.sum(data)
  return data[i,j]/N

In [243]:
joint_probability(data, 1,1)

0.022222222222222223

X가 xi 값을 가질 확률도 구할 수 있다. 해당 행에 있는 포인트들의 숫자를 전체 포인트들의 숫자로 나눠서 구한다.

In [244]:
def joint_probability_row(data, n):
  """
  n 행의 값을 가질 확률
  Args:
    data : 행렬 형태의 전체 데이터
    n : 행 번호
  Return
    n 행의 값을 가질 확률
  """
  sum = 0
  N = np.sum(data)

  for i in range(data.shape[0]):
    sum += data[n,i]
  return sum/N

In [245]:
def joint_probability_col(data, n):
  """
  n 열의 값을 가질 확률
  Args:
    data : 행렬 형태의 전체 데이터
    n : 열 번호
  Return
    n 열의 값을 가질 확률
  """
  sum = 0
  N = np.sum(data)

  for i in range(data.shape[0]):
    sum += data[i,n]
  return sum/N

In [246]:
joint_probability_row(data, 1)

0.17037037037037037

i행에 있는 사례의 숫자는 해당 행의 각 칸에 있는 사례의 숫자 합이다. 이것이 확률의 합의 법칙이다.

In [247]:
sum = 0
for i in range(data.shape[1]):
  sum += joint_probability(data, 1, i)

sum

0.1703703703703704

동일한 결과를 확인할 수 있다.

조건부 확률 X = xi 인 사례들 중 Y = yi 인 사례들의 비율을 생각해 볼 수 있다. 

이를 조건부 확률이라고 한다.

이 확률은 i행에 있는 전체 포인트 수와 i, j 칸에 있는 포인트 수의 비율을 통해서 계산할 수 있다.

In [248]:
def conditional_probability(data, i, j):
  """
  조건부 확률의 계산
  Args:
    data : 
    i : 행 
    j : 열
  Return :
    조건부 확률의 계산값
  """
  return joint_probability(data, i, j) / joint_probability_row(data, i)

In [249]:
conditional_probability(data, 1, 2)

0.21739130434782608

이를 통해 곱의 법칙을 도출해 낼 수 있다. 

In [250]:
joint_probability(data, 1, 2)

0.037037037037037035

In [251]:
conditional_probability(data, 2, 1) * joint_probability_row(data, 1)

0.034074074074074076

곱의 법칙과 대칭성으로부터 조건부 확률 간의 관계를 도출해낼 수 있다.

In [252]:
conditional_probability(data, 1, 2)

0.21739130434782608

In [253]:
conditional_probability(data, 2, 1)*joint_probability_col(data, 1)/joint_probability_row(data, 2)

0.16666666666666666

과일 문제

데이터의 행렬 표현

In [263]:
box = np.array([[0.4],[0.6]]) #빨, 파
box

array([[0.4],
       [0.6]])

In [269]:
fruits = np.array([[2/8,6/8],[3/4,1/4]]) # 사과, 오렌지
fruits

array([[0.25, 0.75],
       [0.75, 0.25]])

원소 곱의 시행

각 열의 합(과일) 은 해당 과일을 고를 전체 확률을 나타낸다.

In [272]:
result = fruits*box
result

array([[0.1 , 0.3 ],
       [0.45, 0.15]])

과일에 대한 상자의 확률은 위 결과에 열 값들의 대한 비율을 통해 얻을 수 있다.

In [281]:
result2 = result
for i in range(result.shape[1]):
  sum = 0
  for j in range(result.shape[0]):
    sum += result[j][i]
  for j in range(result.shape[0]):
    result2[j][i] = result[j][i] / sum

In [282]:
result2

array([[0.10891089, 0.65810429],
       [0.89108911, 0.34189571]])