In [1]:
import numpy as np

행렬 생성

In [2]:
a = np.random.random(16)
a

array([0.36137765, 0.64347275, 0.78088256, 0.14557616, 0.15891768,
       0.29322314, 0.32697214, 0.18413188, 0.41987165, 0.31104381,
       0.83626438, 0.87189381, 0.13557866, 0.85052252, 0.17658111,
       0.76025121])

In [3]:
a.shape

(16,)

In [4]:
a = np.random.random(16).reshape(4,4)
a

array([[0.34341832, 0.41186063, 0.72310685, 0.80852906],
       [0.45525505, 0.05585165, 0.86267619, 0.801103  ],
       [0.73514302, 0.30367276, 0.9453417 , 0.24552262],
       [0.65983331, 0.03270704, 0.3370283 , 0.97283191]])

In [5]:
a.shape

(4, 4)

입력 데이터 생성

In [6]:
input = np.random.random(16).reshape(4,4)
input

array([[0.55281309, 0.96490838, 0.96244924, 0.06141017],
       [0.98767887, 0.19230592, 0.67605589, 0.45613937],
       [0.7133357 , 0.68137346, 0.85323024, 0.6984816 ],
       [0.04180194, 0.33755356, 0.58393166, 0.82826018]])

가중치 커널 생성

In [7]:
w = np.random.random(4).reshape(2,2)
w

array([[0.18120805, 0.03265708],
       [0.13781069, 0.87132649]])

합성곱 신경망의 연산은 커널을 플립하지 않은 연산, cross-corelation 을 더 많이 사용한다.

동일한 두 크기의 행렬의 원소 곱으로 계산할 수 있을 것

In [8]:
row = []
matrix = []

for matrix_row in range(input.shape[0]-w.shape[0]+1):
  for matrix_col in range(input.shape[1]-w.shape[1]+1):
    matrix = []
    for w_row in range(w.shape[0]):
      row = []
      for w_col in range(w.shape[0]):
        row.append(input[matrix_row+w_row,matrix_col+w_col])
      matrix.append(row)
    print(matrix) 

[[0.5528130915124375, 0.9649083842366438], [0.9876788683030719, 0.19230592202556662]]
[[0.9649083842366438, 0.9624492438244256], [0.19230592202556662, 0.6760558938257557]]
[[0.9624492438244256, 0.06141016765953644], [0.6760558938257557, 0.45613936824031365]]
[[0.9876788683030719, 0.19230592202556662], [0.7133356980298609, 0.6813734575430217]]
[[0.19230592202556662, 0.6760558938257557], [0.6813734575430217, 0.8532302422944891]]
[[0.6760558938257557, 0.45613936824031365], [0.8532302422944891, 0.6984815957707333]]
[[0.7133356980298609, 0.6813734575430217], [0.04180194363561962, 0.33755356351307675]]
[[0.6813734575430217, 0.8532302422944891], [0.33755356351307675, 0.5839316553288559]]
[[0.8532302422944891, 0.6984815957707333], [0.5839316553288559, 0.8282601848145766]]


In [9]:
row = []
matrix = []
result = []

for matrix_row in range(input.shape[0]-w.shape[0]+1):
  for matrix_col in range(input.shape[1]-w.shape[1]+1):
    matrix = []
    for w_row in range(w.shape[0]):
      row = []
      for w_col in range(w.shape[0]):
        row.append(input[matrix_row+w_row,matrix_col+w_col])
      matrix.append(row)
    result.append(matrix*w)

In [10]:
result = np.array(result)
result.reshape(9,-1)
result

array([[[0.10017418, 0.03151109],
        [0.13611271, 0.16756124]],

       [[0.17484916, 0.03143078],
        [0.02650181, 0.58906541]],

       [[0.17440355, 0.00200548],
        [0.09316773, 0.39744631]],

       [[0.17897536, 0.00628015],
        [0.09830528, 0.59369874]],

       [[0.03484738, 0.02207801],
        [0.09390055, 0.74344211]],

       [[0.12250677, 0.01489618],
        [0.11758425, 0.60860552]],

       [[0.12926217, 0.02225167],
        [0.00576075, 0.29411936]],

       [[0.12347035, 0.02786401],
        [0.04651849, 0.50879512]],

       [[0.15461218, 0.02281037],
        [0.08047202, 0.72168504]]])

In [11]:
sum_list = []
for i in range(result.shape[0]):
  sum = 0
  for j in range(w.shape[0]):
    for k in range(w.shape[1]):
      sum += result[i][j,k]
  sum_list.append(sum)

In [12]:
sum_list

[0.43535922168438235,
 0.8218471668016154,
 0.6670230659756229,
 0.8772595341132035,
 0.894268050304617,
 0.8635927121227236,
 0.45139395292804346,
 0.7066479711788187,
 0.9795796182389389]

In [13]:
sum_matrix = np.array(sum_list).reshape(input.shape[0]-w.shape[0]+1, input.shape[1]-w.shape[1]+1)
sum_matrix

array([[0.43535922, 0.82184717, 0.66702307],
       [0.87725953, 0.89426805, 0.86359271],
       [0.45139395, 0.70664797, 0.97957962]])

In [14]:
b = sum_matrix + 1 
b

array([[1.43535922, 1.82184717, 1.66702307],
       [1.87725953, 1.89426805, 1.86359271],
       [1.45139395, 1.70664797, 1.97957962]])

패딩의 수행

In [24]:
padding_matrix = np.zeros((input.shape[0]+w.shape[0], input.shape[1]+w.shape[1]))
padding_matrix

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [25]:
input

array([[0.55281309, 0.96490838, 0.96244924, 0.06141017],
       [0.98767887, 0.19230592, 0.67605589, 0.45613937],
       [0.7133357 , 0.68137346, 0.85323024, 0.6984816 ],
       [0.04180194, 0.33755356, 0.58393166, 0.82826018]])

In [26]:
for i in range(input.shape[0]):
  for j in range(input.shape[1]):
    padding_matrix[i+1][j+1] = input[i][j]

In [27]:
padding_matrix

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.55281309, 0.96490838, 0.96244924, 0.06141017,
        0.        ],
       [0.        , 0.98767887, 0.19230592, 0.67605589, 0.45613937,
        0.        ],
       [0.        , 0.7133357 , 0.68137346, 0.85323024, 0.6984816 ,
        0.        ],
       [0.        , 0.04180194, 0.33755356, 0.58393166, 0.82826018,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

스트라이드 적용

In [71]:
row = []
matrix = []
result = []

for matrix_row in range(int((input.shape[0]-w.shape[0])/2)+1):
  for matrix_col in range(int((input.shape[1]-w.shape[1])/2)+1):
    matrix = []
    for w_row in range(w.shape[0]):
      row = []
      for w_col in range(w.shape[1]):
        row.append(input[matrix_row*2+w_row,matrix_col*2+w_col])
      matrix.append(row)
    print(matrix)
    result.append(matrix*w)

[[0.5528130915124375, 0.9649083842366438], [0.9876788683030719, 0.19230592202556662]]
[[0.9624492438244256, 0.06141016765953644], [0.6760558938257557, 0.45613936824031365]]
[[0.7133356980298609, 0.6813734575430217], [0.04180194363561962, 0.33755356351307675]]
[[0.8532302422944891, 0.6984815957707333], [0.5839316553288559, 0.8282601848145766]]


In [53]:
result

[array([[0.10017418, 0.03151109],
        [0.13611271, 0.16756124]]), array([[0.17440355, 0.00200548],
        [0.09316773, 0.39744631]]), array([[0.12926217, 0.02225167],
        [0.00576075, 0.29411936]]), array([[0.15461218, 0.02281037],
        [0.08047202, 0.72168504]])]

In [92]:
def cal_cnn(input, w, stride):
  """
  합성곱 연산
  Args:
    input : 입력값
    w : 가중치, 커널
    stride : 스트라이드 값
  Return:
    합성곱 연산 결과
  """
  row = []
  matrix = []
  result = []
  print(int((input.shape[0]-w.shape[0])/stride)+1)

  # 해당 반복문의 크기는 합성곱 연산 결과와 동일하게 만들어준다.
  # 원소곱을 시행후 행렬들의 생성
  for matrix_row in range(int((input.shape[0]-w.shape[0])/stride)+1):
    for matrix_col in range(int((input.shape[1]-w.shape[1])/stride)+1):
      matrix = []
      for w_row in range(w.shape[0]):
        row = []
        for w_col in range(w.shape[1]):
          row.append(input[matrix_row*stride+w_row,matrix_col*stride+w_col])
        matrix.append(row)
      result.append(matrix*w)
  
  result = np.array(result)
  result.reshape((int((input.shape[0]-w.shape[0])/2)+1)*(int((input.shape[1]-w.shape[1])/2)+1),-1)

  sum_list = []
  for i in range(result.shape[0]):
    sum = 0
    for j in range(w.shape[0]):
      for k in range(w.shape[1]):
        sum += result[i][j,k]
    sum_list.append(sum)

  sum_matrix = np.array(sum_list).reshape(int((input.shape[0]-w.shape[0])/stride)+1, int((input.shape[1]-w.shape[1])/stride)+1)

  return sum_matrix

In [93]:
cal_cnn(input, w, 2)

2


array([[0.43535922, 0.66702307],
       [0.45139395, 0.97957962]])

In [94]:
cal_cnn(input, w, 1)

3


array([[0.43535922, 0.82184717, 0.66702307],
       [0.87725953, 0.89426805, 0.86359271],
       [0.45139395, 0.70664797, 0.97957962]])