In [134]:
from sklearn import datasets

raw_wine = datasets.load_wine()

In [135]:
X = raw_wine.data
y = raw_wine.target

데이터 분할, 표준화

In [136]:
from sklearn.model_selection import train_test_split

X_tn, X_te, y_tn, y_te = train_test_split(X, y, random_state=1)

In [137]:
from sklearn.preprocessing import StandardScaler

std_scale = StandardScaler()
std_scale.fit(X_tn)
X_tn_std = std_scale.transform(X_tn)
X_te_std = std_scale.transform(X_te)

In [138]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
pca.fit(X_tn_std)
X_tn_pca = pca.transform(X_tn_std)
X_te_pca = pca.transform(X_te_std)

In [139]:
pca.get_covariance().shape

(13, 13)

In [140]:
pca.singular_values_ # 고윳값

array([24.81797394, 18.31760391])

In [141]:
pca.components_ # 고유 벡터

array([[-0.10418545,  0.25670612,  0.01387486,  0.23907587, -0.10470229,
        -0.4007005 , -0.42902734,  0.29111343, -0.30307602,  0.12127653,
        -0.31609521, -0.38729685, -0.26283936],
       [-0.49018724, -0.1691503 , -0.30746987,  0.04459018, -0.34837302,
        -0.07966456, -0.0133774 , -0.02498633, -0.0415164 , -0.50798383,
         0.26045807,  0.14018631, -0.39850143]])

In [142]:
pca.get_covariance() # 공분산 행렬

array([[ 1.06244198,  0.05588975,  0.29643474, -0.14674317,  0.38769443,
         0.25079577,  0.19779094, -0.10070718,  0.17126277,  0.44742545,
        -0.12013532,  0.02879752,  0.50505224],
       [ 0.05588975,  0.86510155,  0.11906446,  0.23837434,  0.00721146,
        -0.39785163, -0.4503856 ,  0.31716671, -0.30728109,  0.30100181,
        -0.42357315, -0.45825394, -0.14345856],
       [ 0.29643474,  0.11906446,  0.72597065, -0.01380654,  0.20891722,
         0.02618151, -0.01633577,  0.03209892,  0.00824227,  0.32033554,
        -0.17879769, -0.10868048,  0.2307792 ],
       [-0.14674317,  0.23837434, -0.01380654,  0.77557799, -0.13456582,
        -0.4028355 , -0.42487887,  0.28525095, -0.30301432,  0.07431753,
        -0.28885443, -0.36992936, -0.2952175 ],
       [ 0.38769443,  0.00721146,  0.20891722, -0.13456582,  0.82428285,
         0.22898335,  0.19490044, -0.10843832,  0.16009666,  0.30262412,
        -0.0453494 ,  0.06951315,  0.39222323],
       [ 0.25079577, -0.397851

In [143]:
pca.explained_variance_ # 설명된 분산

array([4.66615023, 2.54192889])

13 개 특성의 133 개 데이터, n=133, p=13

평균 행렬 계산, n,p 의 크기지만 1,p 행렬을 n개 나열한 것으로 대체

In [155]:
X_tn

array([[1.305e+01, 1.770e+00, 2.100e+00, ..., 8.800e-01, 3.350e+00,
        8.850e+02],
       [1.233e+01, 9.900e-01, 1.950e+00, ..., 1.060e+00, 2.310e+00,
        7.500e+02],
       [1.376e+01, 1.530e+00, 2.700e+00, ..., 1.250e+00, 3.000e+00,
        1.235e+03],
       ...,
       [1.349e+01, 1.660e+00, 2.240e+00, ..., 9.800e-01, 2.780e+00,
        4.720e+02],
       [1.293e+01, 2.810e+00, 2.700e+00, ..., 7.700e-01, 2.310e+00,
        6.000e+02],
       [1.305e+01, 1.650e+00, 2.550e+00, ..., 1.120e+00, 2.510e+00,
        1.105e+03]])

In [192]:
X_tn.shape

(133, 13)

각 특성의 평균

In [196]:
mean_matrix = np.mean(X_tn, axis=0)
mean_matrix

array([1.29755639e+01, 2.42052632e+00, 2.36165414e+00, 1.96421053e+01,
       9.87518797e+01, 2.25699248e+00, 1.97255639e+00, 3.68947368e-01,
       1.56255639e+00, 5.03962405e+00, 9.58315789e-01, 2.57345865e+00,
       7.42721805e+02])

평균과 각 데이터의 편차 계산

In [197]:
deviation_matrix = X_tn - mean_matrix
deviation_matrix

array([[ 7.44360902e-02, -6.50526316e-01, -2.61654135e-01, ...,
        -7.83157895e-02,  7.76541353e-01,  1.42278195e+02],
       [-6.45563910e-01, -1.43052632e+00, -4.11654135e-01, ...,
         1.01684211e-01, -2.63458647e-01,  7.27819549e+00],
       [ 7.84436090e-01, -8.90526316e-01,  3.38345865e-01, ...,
         2.91684211e-01,  4.26541353e-01,  4.92278195e+02],
       ...,
       [ 5.14436090e-01, -7.60526316e-01, -1.21654135e-01, ...,
         2.16842105e-02,  2.06541353e-01, -2.70721805e+02],
       [-4.55639098e-02,  3.89473684e-01,  3.38345865e-01, ...,
        -1.88315789e-01, -2.63458647e-01, -1.42721805e+02],
       [ 7.44360902e-02, -7.70526316e-01,  1.88345865e-01, ...,
         1.61684211e-01, -6.34586466e-02,  3.62278195e+02]])

In [198]:
deviation_matrix.shape

(133, 13)

편차 행렬의 제곱, 행렬 곱을 통해 계산 

해당 행렬의 평균값이 공분산 행렬

In [199]:
deviation_matrix2 = deviation_matrix.T @ deviation_matrix
deviation_matrix2.shape

(13, 13)

In [201]:
covariance_matrix = deviation_matrix2 / deviation_matrix.shape[0]
covariance_matrix

array([[ 6.27370547e-01,  7.23985754e-02,  4.88983153e-02,
        -7.55459834e-01,  2.69596699e+00,  1.26940042e-01,
         1.48968483e-01, -1.13738425e-02,  3.09173554e-02,
         1.03786525e+00, -2.16799525e-02,  2.12048166e-02,
         1.42645382e+02],
       [ 7.23985754e-02,  1.35972228e+00,  4.56660467e-02,
         1.21962446e+00, -6.59042343e-01, -2.48721725e-01,
        -4.83544954e-01,  3.48855164e-02, -1.15764503e-01,
         6.28568619e-01, -1.64964226e-01, -3.13945429e-01,
        -7.66388761e+01],
       [ 4.88983153e-02,  4.56660467e-02,  7.46709480e-02,
         4.11930352e-01,  1.25552321e+00,  1.96591102e-02,
         2.35461473e-02,  6.22730510e-03, -2.20873989e-03,
         1.48029946e-01, -3.95435694e-03,  1.00254961e-03,
         1.90676782e+01],
       [-7.55459834e-01,  1.21962446e+00,  4.11930352e-01,
         1.05616858e+01, -3.78278591e+00, -6.39843292e-01,
        -1.14261140e+00,  1.28811239e-01, -3.47859517e-01,
         1.12128612e-01, -2.13847883e

구한 행렬의 대각 행렬은 각 특성에 대한 분산

행렬의 (i,j) 원소는 i, j 에 대한 공분산 j,i 와 i,j 의 공분산의 값은 동일하므로 전치 행렬이 동일하다.

In [203]:
for i in range(covariance_matrix.shape[0]):
  print(covariance_matrix[i][i])

0.627370546667421
1.3597222793826673
0.07467094804680868
10.561685793430946
187.72039120357255
0.3962315563344451
1.011191961105772
0.014302651365255237
0.34046865283509514
5.701612567535766
0.055332622081519574
0.5154241279891456
91149.975238849
