In [76]:
import numpy as np

In [77]:
p_box = np.array(([0.4], [0.6]))
p_box

array([[0.4],
       [0.6]])

In [78]:
red_box = np.array(([2], [6]))
red_box

array([[2],
       [6]])

In [79]:
blue_box = np.array(([3], [1]))
blue_box

array([[3],
       [1]])

In [80]:
p_red_box = red_box / sum(red_box)
p_red_box

array([[0.25],
       [0.75]])

In [81]:
p_blue_box = blue_box / sum(blue_box)
p_blue_box

array([[0.75],
       [0.25]])

In [82]:
p_red_box * p_box[0,0]

array([[0.1],
       [0.3]])

In [83]:
p_blue_box * p_box[1,0]

array([[0.45],
       [0.15]])

In [84]:
a = np.hstack([p_red_box, p_blue_box])
a

array([[0.25, 0.75],
       [0.75, 0.25]])

In [85]:
p_box2 = (a.T * p_box).T
p_box2

array([[0.1 , 0.45],
       [0.3 , 0.15]])

In [86]:
p_box2_sum = p_box2.sum(axis=0).reshape(2,-1)
p_box2_sum

array([[0.4],
       [0.6]])

In [87]:
p_c_box = p_box2 / p_box2_sum.T
p_c_box

array([[0.25, 0.75],
       [0.75, 0.25]])

In [90]:
p_box2_sum2 = p_box2.sum(axis=1).reshape(2,-1)
p_box2_sum2

array([[0.55],
       [0.45]])

In [97]:
p_c_box[1,0] * p_box[0,0] / p_box2_sum2[1,0]

0.6666666666666666

In [102]:
p_c_box[1,1] * p_box[1,0] / p_box2_sum2[1,0]

0.33333333333333326

In [103]:
p_c_box[0,0] * p_box[0,0] / p_box2_sum2[0,0]

0.18181818181818185

In [104]:
p_c_box[0,1] * p_box[1,0] / p_box2_sum2[0,0]

0.8181818181818182

In [107]:
p_c_box * p_box / p_box2_sum2.T

array([[0.18181818, 0.66666667],
       [0.81818182, 0.33333333]])