In [34]:
import numpy as np

In [35]:
p_box = np.array(([0.4], [0.6]))
p_box

array([[0.4],
       [0.6]])

In [36]:
red_box = np.array(([2], [6]))
red_box

array([[2],
       [6]])

In [37]:
blue_box = np.array(([3], [1]))
blue_box

array([[3],
       [1]])

In [38]:
p_red_box = red_box / sum(red_box)
p_red_box

array([[0.25],
       [0.75]])

In [39]:
p_blue_box = blue_box / sum(blue_box)
p_blue_box

array([[0.75],
       [0.25]])

In [40]:
p_red_box * p_box[0,0]

array([[0.1],
       [0.3]])

In [41]:
p_blue_box * p_box[1,0]

array([[0.45],
       [0.15]])

In [42]:
a = np.hstack([p_red_box, p_blue_box])
a

array([[0.25, 0.75],
       [0.75, 0.25]])

In [43]:
p_box2 = (a.T * p_box).T
p_box2

array([[0.1 , 0.45],
       [0.3 , 0.15]])