In [2]:
import numpy as np

In [3]:
confusion_matrix = np.random.randint(0,100,4).reshape(2,2)
confusion_matrix

array([[23,  7],
       [14, 35]])

In [5]:
cost_matrix = np.array(([0,10],[1,0]))
cost_matrix

array([[ 0, 10],
       [ 1,  0]])

In [7]:
loss = confusion_matrix * cost_matrix
loss

array([[ 0, 70],
       [14,  0]])

In [10]:
loss_sum = np.sum(loss)
loss_sum

84