In [3]:
import numpy as np

In [4]:
mu = 0.7

In [5]:
Bern_x = mu**1 * (1-mu)**(1-1)
Bern_x

0.7

In [6]:
MU = np.array(([0.7],[0.3]))
MU

array([[0.7],
       [0.3]])

In [11]:
X = np.array(([0],[1]))
X

array([[0],
       [1]])

In [9]:
Bern = MU**X * (1-MU)**(1-X)
Bern

array([[0.3],
       [0.3]])

In [10]:
MU**X

array([[1. ],
       [0.3]])

In [12]:
1 - MU

array([[0.3],
       [0.7]])

In [13]:
1 - X

array([[1],
       [0]])

In [14]:
(1 - MU)**(1-X)

array([[0.3],
       [1. ]])

In [19]:
ones = np.ones((1,70))
ones.shape

(1, 70)

In [20]:
zeros = np.zeros((1,30))
zeros.shape

(1, 30)

In [23]:
data = np.concatenate((ones, zeros), axis=1)
data

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [27]:
a,b = np.where(data==0)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
b

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,
       87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [32]:
c, d = np.where(data == 1)
c

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0])

In [33]:
mu_ML = np.array(([c.shape[0] / data.shape[1]], [a.shape[0] / data.shape[1]]))
mu_ML

array([[0.7],
       [0.3]])

이항 분포

In [34]:
N_m = np.array(([100],[70]))
N_m

array([[100],
       [ 70]])