In [1]:
import numpy as np

In [2]:
a = np.zeros((70))
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.])

In [3]:
b = np.ones((30))
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
data = np.concatenate((a,b))
data

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
data.shape[0]

100

In [6]:
data[99]

1.0

In [7]:
for i in range(0,int(data.shape[0]*0.7)):
  print(np.random.randint(0,int(data.shape[0]*0.7)-i), int(data.shape[0]*0.7)-i)

58 70
58 69
23 68
29 67
44 66
53 65
10 64
11 63
18 62
40 61
57 60
19 59
54 58
43 57
26 56
5 55
36 54
28 53
17 52
33 51
14 50
17 49
36 48
30 47
30 46
39 45
5 44
32 43
6 42
39 41
26 40
12 39
32 38
18 37
1 36
34 35
5 34
27 33
2 32
19 31
13 30
26 29
4 28
4 27
23 26
16 25
16 24
4 23
6 22
18 21
4 20
8 19
2 18
10 17
3 16
2 15
4 14
4 13
2 12
0 11
5 10
0 9
7 8
0 7
0 6
2 5
1 4
1 3
0 2
0 1


In [8]:
def data_division(data, ratio):
  train_data = []
  data_size = data.shape[0]
  for i in range(0,int(data_size*ratio)):
    rand_int = np.random.randint(0,data_size-i)
    train_data.append(data[rand_int])
    data = np.delete(data, rand_int)

  test_data = data

  return np.array(train_data), np.array(test_data)

In [9]:
train_data, test_data = data_division(data, 0.7)

In [10]:
train_data

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0.,
       0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 1.,
       0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 0.])

In [11]:
test_data

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
def stratified(data, ratio):
  np.unique(data)

In [19]:
a, b = np.unique(data, return_counts=True)
a

array([0., 1.])

In [17]:
b

array([70, 30])

In [31]:
for i in range(0, a.shape[0]):
  label_rate = []
  data_count = sum(b)
  label_rate.append(b/data_count)  

In [32]:
label_rate

[array([0.7, 0.3])]

In [25]:
b[0]

70

In [34]:
data_0 = data[data == a[0]]
data_0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.])

In [109]:
def stratified(data, ratio):
  a, b = np.unique(data, return_counts=True)
  train_count = b * ratio
  label_data = []
  train_data = []
  test_data = []
  for i in range(0, a.shape[0]):
    label_data.append(data[data == a[i]])

    #각 레이블 별 데이터 세트 개수
    data_size = int(len(label_data[i]) * ratio)

    label_data_np = np.array(label_data[i])

    for j in range(0, data_size):
      rand_int = np.random.randint(0,data_size-j)
      train_data.append(label_data_np[rand_int])
      label_data_np = np.delete(label_data_np, rand_int)
    
    for j in range(0, label_data_np.shape[0]):
      test_data.append(label_data_np[j])

  return train_data, test_data

In [110]:
train_data, test_data = stratified(data, 0.7)

In [111]:
len(test_data)

30

In [112]:
len(train_data)

70

In [114]:
a, b = np.unique(test_data, return_counts=True)
b

array([21,  9])

In [115]:
a, b = np.unique(train_data, return_counts=True)
b

array([49, 21])