무작위 선형 데이터 생성

In [27]:
import numpy as np

X = 2*np.random.rand(100,1)
y = 4+3*X+np.random.randn(100,1)

정규 방정식을 사용한 가중치 계산

1.최소 제곱법을 통해서 오차의 제곱합을 구한다.
2.가중치 변화에 따른 오차의 변화가 최소가 되는 가중치 탐색(미분한 값이 0이 되도록)

In [28]:
X_b = np.c_[np.ones((100, 1)), X]
theta_best = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y)

In [29]:
theta_best

array([[3.89535721],
       [3.06814555]])

릿지회귀 분석(L2 제약식)

회귀 분석 최적화 모형에서 가중치 요소 제곱합이 t보다 작다는 제약식이 추가된 형태

shrinkage parameter 를 통한 릿지 회귀 조정

In [30]:
shrinkage_parameter = 0.1

단위 행렬 생성, shtinkage_parameter와의 곱

In [31]:
X_b.shape

(100, 2)

In [32]:
unit_matrix = np.eye(2)
unit_matrix = unit_matrix*shrinkage_parameter
unit_matrix

array([[0.1, 0. ],
       [0. , 0.1]])

기존의 정규방정식에
오차 제곱에 shrinkage_parameter의 합을 더한 값에 연산을 수행한다.

In [33]:
theta_best_l2 = np.linalg.inv(X_b.T.dot(X_b)+unit_matrix).dot(X_b.T).dot(y)
theta_best_l2

array([[3.88884539],
       [3.0707521 ]])

In [34]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X, y)

LinearRegression()

In [35]:
print(lin_reg.intercept_, lin_reg.coef_, theta_best)

[3.89535721] [[3.06814555]] [[3.89535721]
 [3.06814555]]


In [36]:
from sklearn.linear_model import Lasso
lin_reg_l2 = Lasso(alpha=shrinkage_parameter)
lin_reg_l2.fit(X, y)

Lasso(alpha=0.1)

In [37]:
print(lin_reg_l2.intercept_, lin_reg_l2.coef_, theta_best_l2)

[4.20665598] [2.75879549] [[3.88884539]
 [3.0707521 ]]
