In [40]:
import numpy as np

X = 2*np.random.rand(100,1)
y = 4+3*X+np.random.randn(100,1)

In [41]:
X_b = np.c_[np.ones((100, 1)), X]
X.shape

(100, 1)

In [42]:
theta = np.random.randn(2,1)
theta

array([[-0.8998232 ],
       [ 0.52211289]])

경사 하강법 구현
비용 함수의 편도 함수

1.비용함수

가중치의 전치 행렬과 각 입력(편향의 1이 추가된)의 내적(결과)과 출력을 뺀 값, 오차 제곱 합의 평균

In [43]:
from sympy import Derivative, symbols

sum = 0
for i in range(X.shape[0]):
  sum += (theta.T.dot(X_b[i])-y[i])**2

sum

array([5443.55297605])

In [44]:
mse = sum/X.shape[0]
mse

array([54.43552976])

가중치 변화에 따른 오차에 변화를 측정해야 함

가중치 기준으로 한 미분값을 얻어야

벡터의 미분을 어떻게 얻을지?

theta 의 변화량에 따른 오차의 변화를 측정해야 함

점곱의 구현 필요, 편미분의 구현 필요

벡터의 미분을 미리 계산한 것을 사용하는 것이 일반화가 더 좋을 것

비용 함수의 그레이디언트 벡터

2/mX^T(Xa-y)

배치 경사 하강법

In [113]:
eta = 0.1
n_iterations = 1000
m = 100

In [114]:
theta2 = np.random.randn(2,1)

In [115]:
print(theta2.shape, X_b.shape, y.shape)

(2, 1) (100, 2) (100, 1)


In [116]:
for iteration in range(n_iterations):
  gradients = 2/m * ((theta2.T.dot(X_b.T) - y.T).dot(X_b).T)
  theta2 = theta2 - eta*gradients

In [117]:
theta = np.random.randn(2,1)

for iteration in range(n_iterations):
  gradients = 2/m * X_b.T.dot(X_b.dot(theta)-y)
  theta = theta - eta*gradients

In [118]:
theta

array([[3.69690495],
       [3.20990575]])

In [119]:
theta2

array([[3.69690495],
       [3.20990575]])

확률적 경사 하강법

총 50회의 반복, 100개의 샘플을 가진 배치 추출

학습 스케줄의 조절, 반복 횟수가 늘어날 수록 학습률을 감소시킨다.

In [48]:
n_epochs = 50
t0, t1 = 5, 50
m = 100

def learning_schedule(t):
  print(t, t0, t1, t0 / (t+t1))
  return t0 / (t+t1)

theta = np.random.randn(2,1)

for epoch in range(n_epochs):
  for i in range(m):
    random_index = np.random.randint(m)
    xi = X_b[random_index:random_index+1]
    yi = y[random_index:random_index+1]

    gradients = 2*xi.T.dot(xi.dot(theta)-yi)
    eta = learning_schedule(epoch*m+i)
    theta = theta - eta*gradients

0 5 50 0.1
1 5 50 0.09803921568627451
2 5 50 0.09615384615384616
3 5 50 0.09433962264150944
4 5 50 0.09259259259259259
5 5 50 0.09090909090909091
6 5 50 0.08928571428571429
7 5 50 0.08771929824561403
8 5 50 0.08620689655172414
9 5 50 0.0847457627118644
10 5 50 0.08333333333333333
11 5 50 0.08196721311475409
12 5 50 0.08064516129032258
13 5 50 0.07936507936507936
14 5 50 0.078125
15 5 50 0.07692307692307693
16 5 50 0.07575757575757576
17 5 50 0.07462686567164178
18 5 50 0.07352941176470588
19 5 50 0.07246376811594203
20 5 50 0.07142857142857142
21 5 50 0.07042253521126761
22 5 50 0.06944444444444445
23 5 50 0.0684931506849315
24 5 50 0.06756756756756757
25 5 50 0.06666666666666667
26 5 50 0.06578947368421052
27 5 50 0.06493506493506493
28 5 50 0.0641025641025641
29 5 50 0.06329113924050633
30 5 50 0.0625
31 5 50 0.06172839506172839
32 5 50 0.06097560975609756
33 5 50 0.060240963855421686
34 5 50 0.05952380952380952
35 5 50 0.058823529411764705
36 5 50 0.05813953488372093
37 5 50 0.05747

In [49]:
theta

array([[3.66467185],
       [3.24938153]])

In [50]:
from sklearn.linear_model import SGDRegressor
sgd_reg = SGDRegressor(max_iter=1000, tol=0.001, eta0=0.1)