In [22]:
import numpy as np

In [23]:
np.random.random(10)

array([0.11002549, 0.89292016, 0.18191698, 0.29125905, 0.75213597,
       0.19003221, 0.92413057, 0.22093307, 0.34410257, 0.73407713])

In [24]:
a_1 = np.random.uniform(0,1,10).reshape(1,10)
a_1

array([[0.03469035, 0.75268437, 0.87531154, 0.070726  , 0.48743429,
        0.68499242, 0.35791091, 0.94000895, 0.1697126 , 0.67921846]])

In [25]:
a_2 = np.random.uniform(3,5,10).reshape(1,10)
a_2

array([[4.34678827, 3.77574155, 4.67685232, 3.43667384, 3.19231599,
        3.68352198, 3.50401283, 3.35793393, 4.66404846, 3.00791598]])

In [26]:
b_1 = np.random.uniform(5,10,10).reshape(1,10)
b_1

array([[7.33868828, 7.75959245, 5.59262272, 6.42270982, 5.33400013,
        8.87724871, 6.24702906, 8.4271758 , 7.54124974, 6.53569375]])

In [27]:
b_2 = np.random.uniform(2,3,10).reshape(1,10)
b_2

array([[2.60458277, 2.44726742, 2.33649348, 2.34075202, 2.8604337 ,
        2.36797659, 2.37990476, 2.23774693, 2.1385798 , 2.18587848]])

In [28]:
a_1.shape

(1, 10)

In [29]:
a = np.concatenate((a_1,a_2), axis=1)
a

array([[0.03469035, 0.75268437, 0.87531154, 0.070726  , 0.48743429,
        0.68499242, 0.35791091, 0.94000895, 0.1697126 , 0.67921846,
        4.34678827, 3.77574155, 4.67685232, 3.43667384, 3.19231599,
        3.68352198, 3.50401283, 3.35793393, 4.66404846, 3.00791598]])

In [30]:
b = np.concatenate((b_1,b_2), axis=1)
b

array([[7.33868828, 7.75959245, 5.59262272, 6.42270982, 5.33400013,
        8.87724871, 6.24702906, 8.4271758 , 7.54124974, 6.53569375,
        2.60458277, 2.44726742, 2.33649348, 2.34075202, 2.8604337 ,
        2.36797659, 2.37990476, 2.23774693, 2.1385798 , 2.18587848]])

In [33]:
data = np.concatenate((a,b),axis=0)
data

array([[0.03469035, 0.75268437, 0.87531154, 0.070726  , 0.48743429,
        0.68499242, 0.35791091, 0.94000895, 0.1697126 , 0.67921846,
        4.34678827, 3.77574155, 4.67685232, 3.43667384, 3.19231599,
        3.68352198, 3.50401283, 3.35793393, 4.66404846, 3.00791598],
       [7.33868828, 7.75959245, 5.59262272, 6.42270982, 5.33400013,
        8.87724871, 6.24702906, 8.4271758 , 7.54124974, 6.53569375,
        2.60458277, 2.44726742, 2.33649348, 2.34075202, 2.8604337 ,
        2.36797659, 2.37990476, 2.23774693, 2.1385798 , 2.18587848]])

In [34]:
data.shape

(2, 20)

In [36]:
target_1 = np.zeros((1,10))
target_1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [37]:
target_2 = np.ones((1,10))
target_2

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [38]:
target = np.concatenate((target_1, target_2), axis=1)
target

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [39]:
target.shape

(1, 20)