In [1]:
import numpy as np

랜덤 데이터 생성

In [64]:
np.random.seed(42)

a = np.array(np.random.random(10)).reshape(-1,10)
b = np.array(np.random.random(10)).reshape(-1,10)

In [65]:
print(a, b)

[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
  0.05808361 0.86617615 0.60111501 0.70807258]] [[0.02058449 0.96990985 0.83244264 0.21233911 0.18182497 0.18340451
  0.30424224 0.52475643 0.43194502 0.29122914]]


분산 계산

In [66]:
a_variance = np.var(a)
a_variance

0.08979398245355814

In [30]:
def variance(a):
  a_mean = np.mean(a)
  return np.mean((a-a_mean)**2)

In [31]:
variance(a)

0.08979398245355814

In [34]:
def variance2(a):
  a_mean = np.mean(a)
  return np.mean(a**2)-a_mean**2

In [35]:
variance2(a)

0.08979398245355813

공분산

In [16]:
np.cov(a, b)

array([[0.09977109, 0.06726516],
       [0.06726516, 0.09142799]])

In [17]:
np.cov(b,a)

array([[0.09142799, 0.06726516],
       [0.06726516, 0.09977109]])

In [18]:
np.cov(a,a)

array([[0.09977109, 0.09977109],
       [0.09977109, 0.09977109]])

In [21]:
def convariance(a, b):
  a_mean = np.mean(a)
  b_mean = np.mean(b)

  ab = (a-a_mean)*(b-b_mean)
  return np.mean(np.sum(ab))

In [22]:
convariance(a,b)

0.6053864033673627

In [25]:
convariance(b,a)

0.6053864033673627

In [38]:
np.cov(a)

array(0.09977109)

In [39]:
np.cov(a,b)

array([[0.09977109, 0.06726516],
       [0.06726516, 0.09142799]])

In [44]:
a2 = np.array([0,1,2])
b2 = np.array([2,1,0])

In [45]:
np.cov(a2,b2)

array([[ 1., -1.],
       [-1.,  1.]])

In [46]:
convariance(a2,b2)

-2.0

다른 방식으로 분산의 계산

In [26]:
def convariance2(a,b):
  ab_mean = np.mean(a*b)
  a_mean = np.mean(a)
  b_mean = np.mean(b)
  return ab_mean - a_mean*b_mean

In [27]:
convariance2(a,b)

0.06053864033673623

In [28]:
np.var(a)

0.08979398245355814

In [29]:
np.cov(a,a)

array([[0.09977109, 0.09977109],
       [0.09977109, 0.09977109]])

In [72]:
matrix = np.concatenate([a,b], 0)
matrix

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
        0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497,
        0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914]])

In [87]:
matrix.shape

(2, 10)

In [90]:
matrix_mean = np.mean(matrix, axis=0).reshape(-1,10)
matrix_mean

array([[0.19756231, 0.96031208, 0.78221829, 0.4054988 , 0.1689218 ,
        0.16969952, 0.18116293, 0.69546629, 0.51653002, 0.49965086]])

In [91]:
matrix_mean.shape

(1, 10)

In [92]:
matrix_deviation = matrix-matrix_mean
matrix_deviation

array([[ 0.17697781, -0.00959777, -0.05022435,  0.19315969, -0.01290316,
        -0.01370499, -0.12307932,  0.17070986,  0.084585  ,  0.20842172],
       [-0.17697781,  0.00959777,  0.05022435, -0.19315969,  0.01290316,
         0.01370499,  0.12307932, -0.17070986, -0.084585  , -0.20842172]])

In [94]:
matrix_deviation.shape

(2, 10)

In [95]:
(matrix_deviation@matrix_deviation.T)/2

array([[ 0.08324267, -0.08324267],
       [-0.08324267,  0.08324267]])