In [230]:
import numpy as np

랜덤 데이터 생성

In [231]:
np.random.seed(42)

a = np.array(np.random.random(10)).reshape(-1,10)
b = np.array(np.random.random(10)).reshape(-1,10)

In [232]:
print(a, b)

[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
  0.05808361 0.86617615 0.60111501 0.70807258]] [[0.02058449 0.96990985 0.83244264 0.21233911 0.18182497 0.18340451
  0.30424224 0.52475643 0.43194502 0.29122914]]


분산 계산

In [233]:
a_variance = np.var(a)
a_variance

0.08979398245355814

In [234]:
def variance(a):
  a_mean = np.mean(a)
  return np.mean((a-a_mean)**2)

In [235]:
variance(a)

0.08979398245355814

In [236]:
def variance2(a):
  a_mean = np.mean(a)
  return np.mean(a**2)-a_mean**2

In [237]:
variance2(a)

0.08979398245355813

공분산

In [238]:
np.cov(a, b)

array([[0.09977109, 0.06726516],
       [0.06726516, 0.09142799]])

In [239]:
np.cov(b,a)

array([[0.09142799, 0.06726516],
       [0.06726516, 0.09977109]])

In [240]:
np.cov(a,a)

array([[0.09977109, 0.09977109],
       [0.09977109, 0.09977109]])

In [241]:
def convariance(a, b):
  a_mean = np.mean(a)
  b_mean = np.mean(b)

  ab = (a-a_mean)*(b-b_mean)
  return np.mean(ab)

In [242]:
convariance(a,b)

0.06053864033673627

In [243]:
np.cov(a, b)

array([[0.09977109, 0.06726516],
       [0.06726516, 0.09142799]])

다른 방식으로 분산의 계산

In [244]:
def convariance2(a,b):
  ab_mean = np.mean(a*b)
  a_mean = np.mean(a)
  b_mean = np.mean(b)
  return ab_mean - a_mean*b_mean

순서와는 상관이 없다

In [245]:
convariance2(a,b)

0.06053864033673623

In [246]:
convariance2(b,a)

0.06053864033673623

X끼리의 공분산은 분산과 같다

In [247]:
convariance(a,a)

0.08979398245355814

In [248]:
variance(a)

0.08979398245355814

In [249]:
matrix = np.concatenate([a,b], 0)
matrix

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
        0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497,
        0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914]])

In [250]:
matrix.shape

(2, 10)

In [251]:
matrix_mean = np.mean(matrix, axis=0).reshape(-1,10)
matrix_mean

array([[0.19756231, 0.96031208, 0.78221829, 0.4054988 , 0.1689218 ,
        0.16969952, 0.18116293, 0.69546629, 0.51653002, 0.49965086]])

In [252]:
matrix_mean.shape

(1, 10)

In [253]:
matrix_deviation = matrix-matrix_mean
matrix_deviation

array([[ 0.17697781, -0.00959777, -0.05022435,  0.19315969, -0.01290316,
        -0.01370499, -0.12307932,  0.17070986,  0.084585  ,  0.20842172],
       [-0.17697781,  0.00959777,  0.05022435, -0.19315969,  0.01290316,
         0.01370499,  0.12307932, -0.17070986, -0.084585  , -0.20842172]])

In [254]:
matrix_deviation.shape

(2, 10)

In [255]:
(matrix_deviation@matrix_deviation.T)/2

array([[ 0.08324267, -0.08324267],
       [-0.08324267,  0.08324267]])

In [256]:
m = np.arange(10, dtype=np.float64)
f = np.arange(10) * 2

In [257]:
m

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [258]:
f

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [259]:
mean = np.mean(m)
mean

4.5

In [260]:
var = np.var(m)
var # 분산

8.25

In [261]:
var**(1/2) # 표준 편차

2.8722813232690143

In [263]:
np.var(m)

8.25

In [264]:
convariance(m,m)

8.25

In [265]:
variance(m)

8.25

In [267]:
convariance(m,f)

16.5

In [272]:
matrix = np.concatenate([m,f], 0).reshape(2,10)
matrix

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.]])

In [273]:
matrix_mean = np.mean(matrix, axis=0)
matrix_mean

array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5, 12. , 13.5])

In [276]:
matrix_deviation = matrix - matrix_mean
matrix_deviation

array([[ 0. , -0.5, -1. , -1.5, -2. , -2.5, -3. , -3.5, -4. , -4.5],
       [ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5]])

In [278]:
matrix_deviation@(matrix_deviation.T)

array([[ 71.25, -71.25],
       [-71.25,  71.25]])

0.0